defaults: &defaults
  url: <%= Rails.application.credentials.REDIS[:URL] %>
  password: <%= Rails.application.credentials.REDIS[:PASSWORD] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
